### IMPORTANT ###
# This file needs to be refactored. Check if the image names are up-to-date

version: "3.4"
services:
  frontend:
    image: miel1980/open-trivia-frontend
    ports:
      - 80:80
    networks:
      - open-trivia-app-network
  backend:
    image: miel1980/open-trivia-api
    hostname: backend
    ports:
      - 10001:10001
    networks:
      - open-trivia-app-network

networks:
  open-trivia-app-network:
    driver: overlay